language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
install:
    - pip install pytest flake8 sphinx
script:
    - py.test
    - "flake8 . --ignore='E128'"
    - sphinx-build -W -bhtml docs/ docs/_build/html/
